# Always use smart-case search
--smart-case

# Include hidden files by default
--hidden

# Ignore common bulky folders globally
--glob=!.git/
--glob=!node_modules/

# other useful flags:
# -t only search files of certain type, e.g. -t py
# -T exclude certain type
# -C show lines before and after hits, e.g. -C 2
# -B show lines only before;
# -A show lines only after;
